// Export all custom hooks for easier imports
export { default as useAuth } from "./useAuth";
export { default as useItems } from "./useItems";
export { default as useLocalStorage } from "./useLocalStorage";
export { default as useDebounce } from "./useDebounce";
export { default as usePagination } from "./usePagination";
export { default as useForm } from "./useForm";
export { default as useNotification } from "./useNotification";
export { default as useModal } from "./useModal";
export { default as useConfirm } from "./useConfirm";
